<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BANL11915844b.local" name="testngex.TestNG_AnnotationsEx" tests="8" failures="0" timestamp="3 Sep 2015 22:22:55 GMT" time="0.016" errors="1">
  <testcase name="testcaseLogout" time="0.000" classname="testngex.TestNG_AnnotationsEx"/>
  <testcase name="testcaseForthPriority" time="0.002" classname="testngex.TestNG_AnnotationsEx"/>
  <testcase name="testcaseRegister" time="0.002" classname="testngex.TestNG_AnnotationsEx"/>
  <testcase name="testcaseFirstPriority" time="0.007" classname="testngex.TestNG_AnnotationsEx"/>
  <testcase name="testcaseSecondPriority" time="0.001" classname="testngex.TestNG_AnnotationsEx"/>
  <testcase name="testcaseChangePassword" time="0.004" classname="testngex.TestNG_AnnotationsEx">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at testngex.TestNG_AnnotationsEx.testcaseChangePassword(TestNG_AnnotationsEx.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testcaseChangePassword -->
  <testcase name="testcaseThirdPriority" time="0.000" classname="testngex.TestNG_AnnotationsEx"/>
  <testcase name="testcaseLogin" time="0.000" classname="testngex.TestNG_AnnotationsEx"/>
</testsuite> <!-- testngex.TestNG_AnnotationsEx -->
